# app/modules/waste/disposal_service.py

from uuid import UUID

from sqlalchemy.ext.asyncio import AsyncSession

from app.modules.waste.models import DisposalStep
from app.modules.waste.repository import WasteRepository


class DisposalService:
    """
    Service layer for disposal-step operations.

    Responsibilities:
        - Validate AI-generated disposal instructions
        - Create disposal steps
        - Fetch disposal steps
        - Update step completion
        - Calculate disposal progress
        - Determine category completion
        - Delete disposal steps

    Transaction ownership:
        - create_steps_from_ai() does NOT commit because it is
          normally part of the complete waste-analysis transaction.
        - Standalone update/delete operations commit themselves.

    Repository is responsible only for database operations.
    """

    MAX_DISPOSAL_STEPS = 15
    MAX_INSTRUCTION_LENGTH = 500

    def __init__(
        self,
        session: AsyncSession,
        waste_repository: WasteRepository,
    ):
        self.session = session
        self.waste_repository = waste_repository

    # ========================================================
    # CREATE DISPOSAL STEPS FROM AI
    # ========================================================

    async def create_steps_from_ai(
        self,
        category_result_id: UUID,
        disposal_steps: list[str],
    ) -> list[DisposalStep]:
        """
        Validate and create disposal steps generated by AI.

        IMPORTANT:
        This method does NOT commit.

        It is normally called as part of the complete waste
        analysis transaction.

        Example AI output:

            [
                "Empty and rinse the plastic bottle.",
                "Remove the bottle cap.",
                "Empty the aluminium can.",
                "Flatten the cardboard box."
            ]
        """

        # ----------------------------------------------------
        # Validate AI-generated instructions
        # ----------------------------------------------------

        validated_steps = self._validate_disposal_steps(
            disposal_steps
        )

        # ----------------------------------------------------
        # Persist steps
        # ----------------------------------------------------

        steps = await self.waste_repository.create_disposal_steps(
            category_result_id=category_result_id,
            instructions=validated_steps,
        )

        return steps

    # ========================================================
    # VALIDATE AI DISPOSAL STEPS
    # ========================================================

    def _validate_disposal_steps(
        self,
        disposal_steps: list[str],
    ) -> list[str]:
        """
        Validate and normalize AI-generated disposal steps.

        Rules:
            1. At least one step is required.
            2. Maximum 15 steps.
            3. Every step must be a string.
            4. Empty steps are rejected.
            5. Maximum 500 characters per instruction.
            6. Exact duplicate instructions are removed.
        """

        # ----------------------------------------------------
        # Check existence
        # ----------------------------------------------------

        if not disposal_steps:
            raise ValueError(
                "At least one disposal step is required."
            )

        # ----------------------------------------------------
        # Maximum number of steps
        # ----------------------------------------------------

        if len(disposal_steps) > self.MAX_DISPOSAL_STEPS:
            raise ValueError(
                f"Maximum {self.MAX_DISPOSAL_STEPS} disposal "
                "steps are allowed."
            )

        validated_steps: list[str] = []
        seen_steps: set[str] = set()

        # ----------------------------------------------------
        # Validate each step
        # ----------------------------------------------------

        for step in disposal_steps:

            if not isinstance(step, str):
                raise ValueError(
                    "Each disposal step must be a string."
                )

            # Normalize whitespace
            normalized_step = " ".join(
                step.strip().split()
            )

            # Empty instruction
            if not normalized_step:
                raise ValueError(
                    "Disposal instructions cannot be empty."
                )

            # Maximum instruction length
            if len(normalized_step) > self.MAX_INSTRUCTION_LENGTH:
                raise ValueError(
                    "A disposal instruction exceeds the "
                    f"{self.MAX_INSTRUCTION_LENGTH} character limit."
                )

            # Exact duplicate check
            normalized_key = normalized_step.casefold()

            if normalized_key in seen_steps:
                continue

            seen_steps.add(normalized_key)
            validated_steps.append(normalized_step)

        # ----------------------------------------------------
        # Make sure something valid remains
        # ----------------------------------------------------

        if not validated_steps:
            raise ValueError(
                "No valid disposal steps were provided."
            )

        return validated_steps

    # ========================================================
    # GET DISPOSAL STEPS
    # ========================================================

    async def get_steps(
        self,
        category_result_id: UUID,
    ) -> list[DisposalStep]:
        """
        Get all disposal steps belonging to a category.

        Read-only operation.
        """

        try:
            steps = await self.waste_repository.get_disposal_steps(
                category_result_id=category_result_id,
            )

            return steps

        except Exception:
            await self.session.rollback()
            raise

    # ========================================================
    # UPDATE STEP COMPLETION
    # ========================================================

    async def update_step_completion(
        self,
        step: DisposalStep,
        is_completed: bool,
    ) -> DisposalStep:
        """
        Mark a disposal step as completed or incomplete.

        This is a standalone database operation, therefore
        this method owns its transaction.
        """

        try:
            # ------------------------------------------------
            # Update step
            # ------------------------------------------------

            updated_step = (
                await self.waste_repository.update_step_completion(
                    step=step,
                    is_completed=is_completed,
                )
            )

            # ------------------------------------------------
            # Commit
            # ------------------------------------------------

            await self.session.commit()

            return updated_step

        except Exception:
            await self.session.rollback()
            raise

    # ========================================================
    # CALCULATE PROGRESS
    # ========================================================

    def calculate_progress(
        self,
        steps: list[DisposalStep],
    ) -> tuple[int, int, float]:
        """
        Calculate disposal progress.

        Returns:
            (
                total_steps,
                completed_steps,
                progress_percentage
            )

        Example:

            4 total
            3 completed
            75.0%
        """

        total_steps = len(steps)

        if total_steps == 0:
            return 0, 0, 0.0

        completed_steps = sum(
            1
            for step in steps
            if step.is_completed
        )

        progress_percentage = (
            completed_steps / total_steps
        ) * 100

        return (
            total_steps,
            completed_steps,
            round(progress_percentage, 2),
        )

    # ========================================================
    # CHECK CATEGORY COMPLETION
    # ========================================================

    def is_category_completed(
        self,
        steps: list[DisposalStep],
    ) -> bool:
        """
        Determine whether all disposal steps for a category
        have been completed.

        Empty step list returns False because a category
        without disposal instructions should not be treated
        as successfully completed.
        """

        if not steps:
            return False

        return all(
            step.is_completed
            for step in steps
        )

    # ========================================================
    # DELETE DISPOSAL STEP
    # ========================================================

    async def delete_step(
        self,
        step: DisposalStep,
    ) -> None:
        """
        Delete a disposal step.

        Standalone operation, so this method owns its
        transaction.
        """

        try:
            await self.waste_repository.delete_disposal_step(
                step=step,
            )

            await self.session.commit()

        except Exception:
            await self.session.rollback()
            raise
