"""create rewards tables

Revision ID: 6b3618b4906c
Revises: e680bd007bf1
Create Date: 2026-08-29 15:07:09.891356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b3618b4906c'
down_revision: Union[str, Sequence[str], None] = 'e680bd007bf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reward_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_earned_points', sa.Integer(), nullable=False),
    sa.Column('total_spent_points', sa.Integer(), nullable=False),
    sa.Column('balance_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_wallets_user_id'), 'reward_wallets', ['user_id'], unique=True)
    op.create_table('reward_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('waste_analysis_id', sa.UUID(), nullable=True),
    sa.Column('waste_category_result_id', sa.UUID(), nullable=True),
    sa.Column('disposal_step_id', sa.UUID(), nullable=True),
    sa.Column('transaction_type', sa.Enum('ANALYSIS_REWARD', 'STEP_COMPLETION', 'CATEGORY_COMPLETION', 'ANALYSIS_COMPLETION', 'MARKETPLACE_REDEMPTION', 'ADJUSTMENT', name='reward_transaction_type'), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['disposal_step_id'], ['disposal_steps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['reward_wallets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['waste_analysis_id'], ['waste_analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['waste_category_result_id'], ['waste_category_results.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reward_transactions_analysis_type', 'reward_transactions', ['waste_analysis_id', 'transaction_type'], unique=False)
    op.create_index('ix_reward_transactions_category_type', 'reward_transactions', ['waste_category_result_id', 'transaction_type'], unique=False)
    op.create_index(op.f('ix_reward_transactions_created_at'), 'reward_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_reward_transactions_disposal_step_id'), 'reward_transactions', ['disposal_step_id'], unique=False)
    op.create_index('ix_reward_transactions_step_type', 'reward_transactions', ['disposal_step_id', 'transaction_type'], unique=False)
    op.create_index(op.f('ix_reward_transactions_transaction_type'), 'reward_transactions', ['transaction_type'], unique=False)
    op.create_index('ix_reward_transactions_user_created', 'reward_transactions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_reward_transactions_user_id'), 'reward_transactions', ['user_id'], unique=False)
    op.create_index('ix_reward_transactions_wallet_created', 'reward_transactions', ['wallet_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_reward_transactions_wallet_id'), 'reward_transactions', ['wallet_id'], unique=False)
    op.create_index(op.f('ix_reward_transactions_waste_analysis_id'), 'reward_transactions', ['waste_analysis_id'], unique=False)
    op.create_index(op.f('ix_reward_transactions_waste_category_result_id'), 'reward_transactions', ['waste_category_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reward_transactions_waste_category_result_id'), table_name='reward_transactions')
    op.drop_index(op.f('ix_reward_transactions_waste_analysis_id'), table_name='reward_transactions')
    op.drop_index(op.f('ix_reward_transactions_wallet_id'), table_name='reward_transactions')
    op.drop_index('ix_reward_transactions_wallet_created', table_name='reward_transactions')
    op.drop_index(op.f('ix_reward_transactions_user_id'), table_name='reward_transactions')
    op.drop_index('ix_reward_transactions_user_created', table_name='reward_transactions')
    op.drop_index(op.f('ix_reward_transactions_transaction_type'), table_name='reward_transactions')
    op.drop_index('ix_reward_transactions_step_type', table_name='reward_transactions')
    op.drop_index(op.f('ix_reward_transactions_disposal_step_id'), table_name='reward_transactions')
    op.drop_index(op.f('ix_reward_transactions_created_at'), table_name='reward_transactions')
    op.drop_index('ix_reward_transactions_category_type', table_name='reward_transactions')
    op.drop_index('ix_reward_transactions_analysis_type', table_name='reward_transactions')
    op.drop_table('reward_transactions')
    op.drop_index(op.f('ix_reward_wallets_user_id'), table_name='reward_wallets')
    op.drop_table('reward_wallets')
    # ### end Alembic commands ###
