"""add waste module tables

Revision ID: d98ebd4c0178
Revises: 
Create Date: 2026-08-28 02:13:39.567444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd98ebd4c0178'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_name', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=True)
    op.create_table('email_verification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_user_id'), 'email_verification', ['user_id'], unique=False)
    op.create_table('refresh_token',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_token_user_id'), 'refresh_token', ['user_id'], unique=False)
    op.create_table('reset_password',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reset_password_token_hash'), 'reset_password', ['token_hash'], unique=True)
    op.create_index(op.f('ix_reset_password_user_id'), 'reset_password', ['user_id'], unique=False)
    op.create_table('waste_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ANALYZING', 'ANALYZED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='wasteanalysisstatus'), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waste_analyses_created_at'), 'waste_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_waste_analyses_status'), 'waste_analyses', ['status'], unique=False)
    op.create_index('ix_waste_analyses_user_created', 'waste_analyses', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_waste_analyses_user_id'), 'waste_analyses', ['user_id'], unique=False)
    op.create_table('waste_category_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('waste_analysis_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('RECYCLABLE', 'ORGANIC', 'E_WASTE', 'HAZARDOUS', 'NON_RECYCLABLE', 'COMPOSTABLE', name='wastecategory'), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['waste_analysis_id'], ['waste_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_category_results_analysis_category', 'waste_category_results', ['waste_analysis_id', 'category'], unique=False)
    op.create_index(op.f('ix_waste_category_results_category'), 'waste_category_results', ['category'], unique=False)
    op.create_index(op.f('ix_waste_category_results_waste_analysis_id'), 'waste_category_results', ['waste_analysis_id'], unique=False)
    op.create_table('disposal_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('waste_category_result_id', sa.Uuid(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['waste_category_result_id'], ['waste_category_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_disposal_steps_category_step', 'disposal_steps', ['waste_category_result_id', 'step_number'], unique=False)
    op.create_index(op.f('ix_disposal_steps_waste_category_result_id'), 'disposal_steps', ['waste_category_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disposal_steps_waste_category_result_id'), table_name='disposal_steps')
    op.drop_index('ix_disposal_steps_category_step', table_name='disposal_steps')
    op.drop_table('disposal_steps')
    op.drop_index(op.f('ix_waste_category_results_waste_analysis_id'), table_name='waste_category_results')
    op.drop_index(op.f('ix_waste_category_results_category'), table_name='waste_category_results')
    op.drop_index('ix_category_results_analysis_category', table_name='waste_category_results')
    op.drop_table('waste_category_results')
    op.drop_index(op.f('ix_waste_analyses_user_id'), table_name='waste_analyses')
    op.drop_index('ix_waste_analyses_user_created', table_name='waste_analyses')
    op.drop_index(op.f('ix_waste_analyses_status'), table_name='waste_analyses')
    op.drop_index(op.f('ix_waste_analyses_created_at'), table_name='waste_analyses')
    op.drop_table('waste_analyses')
    op.drop_index(op.f('ix_reset_password_user_id'), table_name='reset_password')
    op.drop_index(op.f('ix_reset_password_token_hash'), table_name='reset_password')
    op.drop_table('reset_password')
    op.drop_index(op.f('ix_refresh_token_user_id'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index(op.f('ix_email_verification_user_id'), table_name='email_verification')
    op.drop_table('email_verification')
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
